name: Data
on: 
  push:
    branches:
      - main

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup the environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Modify files
        run: python test.py
      
      


