name: Data
on: 
  push:
    branches:
      - main

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update the covid data
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
        run: pip install -r requirements.txt & python test.py
      
      


